require 'vagrant-service-manager'
require 'vagrant-registration'

Vagrant.configure(2) do |config|
  config.vm.box = 'box'

  # config.vm.provider 'virtualbox' do |v, override|
  #   v.memory = 1024
  #   v.cpus   = 2
  #   v.customize ['modifyvm', :id, '--ioapic', 'on']
  #   v.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
  # end

  config.registration.skip = true
  config.vm.network 'private_network', ip: '10.10.2.2'

  config.servicemanager.services = 'docker'
end
