inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'build/**/*'

# Offense count: 57
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Metrics/LineLength:
  Max: 120
  Exclude:
    - 'Rakefile'
